### ISSUE TITLE
To be compatible with Node 18

### ISSUE THREAD

**Issue by blurfx** [yorkie-team/yorkie-react-todomvc#8]
**Description:**

When I run a project with Node 18, the following error occurs.
There seems to be a compatibility problem with Node 18 because there is no problem with Node 16.

```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/xo/oss/yorkie-react-todomvc/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/xo/oss/yorkie-react-todomvc/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/xo/oss/yorkie-react-todomvc/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/xo/oss/yorkie-react-todomvc/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/xo/oss/yorkie-react-todomvc/node_modules/webpack/lib/NormalModule.js:35w
/Users/xo/oss/yorkie-react-todomvc/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/xo/oss/yorkie-react-todomvc/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/xo/oss/yorkie-react-todomvc/node_modules/webpack/lib/NormalModule.js:417:16)
    at /Users/xo/oss/yorkie-react-todomvc/node_modules/webpack/lib/NormalModule.js:452:10
    at /Users/xo/oss/yorkie-react-todomvc/node_modules/webpack/lib/NormalModule.js:323:13
    at /Users/xo/oss/yorkie-react-todomvc/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/xo/oss/yorkie-react-todomvc/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/Users/xo/oss/yorkie-react-todomvc/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/xo/oss/yorkie-react-todomvc/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

```

**Why:**
To support the latest stable Node runtime.

**Comment by 2kindsofcs** [comment]
Hi. I want to give it a try. can I take this one? (btw, I'm new to the project.)

**Comment by blurfx** [comment]
@2kindsofcs Sure 🙂
